### ISSUE TITLE
No such file or directory @ rb_sysopen - tmp/pids/sidekiq.pid

### ISSUE THREAD

**Issue by davesag** [upnext/BeaconCtrl#18]
I've been following the Readme to start up a BeaconCtrl server and it almost starts, but for the following error

    15:28:25 web.1    | started with pid 84848
    15:28:25 worker.1 | started with pid 84849
    15:28:27 worker.1 | No such file or directory @ rb_sysopen - /Users/davesag/src/BeaconCtrl/tmp/pids/sidekiq.pid
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:347:in `initialize'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:347:in `open'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:347:in `write_pid'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:42:in `parse'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/gems/sidekiq-3.3.0/bin/sidekiq:7:in `<top (required)>'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/bin/sidekiq:23:in `load'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/bin/sidekiq:23:in `<main>'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    15:28:27 worker.1 | /Users/davesag/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
    15:28:27 worker.1 | exited with code 1
    15:28:27 system   | sending SIGTERM to all processes
    15:28:27 web.1    | terminated by SIGTERM

Any thoughts?

Cheers Dave

**Comment by Tsumanu** [comment]
Please paste me executed command. Is this is master? When you clone it?

**Comment by davesag** [comment]
Hi, yes the master branch and all I did was `bin/setup` and basically just said yes to everything.  I chose Postgres as DB. At the end of the `setup` script it opened a web page with a render of the intro email but in the console I got the above error.

**Comment by Tsumanu** [comment]
I found that tmp/pids directory wasn't created and sidekiq raise Exception when it tries create pid file. I made required fixes. Please pull and rerun ./bin/setup. It should boot correctly.

**Comment by davesag** [comment]
Great yes that fixed the issue.

A few notes as I continue to get this to run:

When the server starts, it starts on port `5000` but the links in the confirmation email that come up refer to port `3000` and so don't work. (raised issue #21 for this)

When I fix the port number I get told that I was `was already confirmed, please try signing in`. But alas I don't have a password to sign in. So I used `forgot my password` to request a reset, the email popped up (again with broken links due to the wrong port) and I reset my password.

On submitting the password reset I got the following error screen

    NoMethodError in Admin::PasswordsController#update
    undefined method `confirmable' for #<ApplicationConfig:0x007ff094e48478>

    Extracted source (around line #37):
    35
    36
    37
    38
    39
                

      def confirmable?(resource)
        AppConfig.confirmable && !resource.active_for_authentication?
      end
    end

    Rails.root: /Users/davesag/src/BeaconCtrl

    Application Trace | Framework Trace | Full Trace
    app/controllers/admin/passwords_controller.rb:37:in `confirmable?'
    app/controllers/admin/passwords_controller.rb:28:in `update_password!'
    app/controllers/admin/passwords_controller.rb:19:in `update'
    Request

    Parameters:

    {"utf8"=>"✓",
     "_method"=>"put",
     "authenticity_token"=>"[FILTERED]",
     "admin"=>{"reset_password_token"=>"[FILTERED]",
     "password"=>"[FILTERED]",
     "password_confirmation"=>"[FILTERED]"},
     "commit"=>"Change password"}

I've raised issue #22 for this

cheers

dave
